"""Build Prestige CSS bundle and content-hashed release manifest.

The TypeScript build (vite + tsc) produces dist/prestige.js and dist/prestige.umd.cjs.
This script concatenates the CSS sources into dist/prestige.css, then generates
content-hashed fingerprints and a manifest.json for both JS and CSS (for SRI).
"""
import hashlib
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC_CSS = ROOT / 'css'
DIST = ROOT / 'dist'
FASTAPI_STATIC = ROOT / 'examples' / 'fastapi-demo' / 'static'
DOCS_DIST = ROOT / 'docs' / 'dist'
DOCS_DEMO = ROOT / 'docs' / 'demo'

CSS_ORDER = [
    'tokens.css',
    'base.css',
    'desktop.css',
    'menubar.css',
    'dock.css',
    'windows.css',
    'context-menu.css',
    'components.css',
    'dialogs.css',
]

def build_css():
    parts = []
    for name in CSS_ORDER:
        path = SRC_CSS / name
        code = path.read_text('utf-8')
        parts.append(f'/* === {name} === */\n')
        parts.append(code)
        parts.append('\n')
    return ''.join(parts)

def main():
    required_files = [
        *(SRC_CSS / name for name in CSS_ORDER),
        DIST / 'prestige.js',
        DIST / 'prestige.umd.cjs',
        DIST / 'index.d.ts',
    ]
    missing_files = [path.relative_to(ROOT) for path in required_files if not path.is_file()]
    if missing_files:
        print('ERROR: required build inputs are missing:', file=sys.stderr)
        for path in missing_files:
            print(f'  - {path}', file=sys.stderr)
        print('Run the TypeScript build first and restore all CSS source modules.', file=sys.stderr)
        return 1

    DIST.mkdir(exist_ok=True)
    FASTAPI_STATIC.mkdir(parents=True, exist_ok=True)
    # Remove only fingerprints generated by this script; stable entrypoints remain.
    for directory in (DIST, FASTAPI_STATIC):
        for path in directory.glob('prestige.*.js'):
            path.unlink()
        for path in directory.glob('prestige.*.css'):
            path.unlink()

    # JS is already built by the TypeScript pipeline. The manifest's prestige.js
    # entry must be the UMD bundle (classic <script> drop-in) named with a .js
    # extension for a correct JS MIME type; the stable ESM entrypoint stays as-is.
    umd_path = DIST / 'prestige.umd.cjs'
    umd_browser_path = DIST / 'prestige.umd.js'
    shutil.copyfile(umd_path, umd_browser_path)

    css = build_css()
    css_path = DIST / 'prestige.css'
    css_path.write_text(css, 'utf-8')
    print(f'Written {len(css)} bytes to dist/prestige.css')

    def fingerprint(path, logical_stem, version_suffix):
        digest = hashlib.sha384(path.read_bytes()).hexdigest()
        suffix = digest[:12]
        versioned_name = f'{logical_stem}.{suffix}{version_suffix}'
        versioned_path = DIST / versioned_name
        shutil.copyfile(path, versioned_path)
        return {
            'file': versioned_name,
            'integrity': f'sha384-{__import__("base64").b64encode(bytes.fromhex(digest)).decode("ascii")}',
        }

    manifest = {
        'prestige.js': fingerprint(umd_path, 'prestige', '.js'),
        'prestige.css': fingerprint(css_path, 'prestige', '.css'),
    }
    (DIST / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n', 'utf-8')
    shutil.copyfile(DIST / 'prestige.js', FASTAPI_STATIC / 'prestige.js')
    shutil.copyfile(DIST / 'prestige.umd.cjs', FASTAPI_STATIC / 'prestige.umd.cjs')
    shutil.copyfile(umd_browser_path, FASTAPI_STATIC / 'prestige.umd.js')
    shutil.copyfile(css_path, FASTAPI_STATIC / 'prestige.css')
    for item in manifest.values():
        shutil.copyfile(DIST / item['file'], FASTAPI_STATIC / item['file'])
    shutil.copyfile(DIST / 'manifest.json', FASTAPI_STATIC / 'manifest.json')
    print('Written dist/manifest.json and synchronized content-hashed FastAPI assets')

    # GitHub Pages: docs/ is the site root, so vendored copies live under docs/.
    # docs/dist/ backs the marketing page download links; docs/demo/ is the live demo.
    for directory in (DOCS_DIST, DOCS_DEMO):
        directory.mkdir(parents=True, exist_ok=True)
    for directory in (DOCS_DIST, DOCS_DEMO):
        for path in directory.glob('prestige.*.js'):
            path.unlink()
        for path in directory.glob('prestige.*.css'):
            path.unlink()
    for filename in ('prestige.umd.cjs', 'prestige.umd.js', 'prestige.js', 'prestige.css', 'manifest.json'):
        shutil.copyfile(DIST / filename, DOCS_DIST / filename)
        shutil.copyfile(DIST / filename, DOCS_DEMO / filename)
    for declaration in DIST.rglob('*.d.ts'):
        relative = declaration.relative_to(DIST)
        for directory in (DOCS_DIST, DOCS_DEMO):
            target = directory / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(declaration, target)
    for item in manifest.values():
        shutil.copyfile(DIST / item['file'], DOCS_DIST / item['file'])
        shutil.copyfile(DIST / item['file'], DOCS_DEMO / item['file'])
    print('Synchronized GitHub Pages assets: docs/dist/ and docs/demo/')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
