"""Generate the curated Lucide runtime registry from the pinned SVG snapshot."""

from collections import OrderedDict
from pathlib import Path
import json
import re


ROOT = Path(__file__).resolve().parent.parent
ICON_DIR = ROOT / "vendor" / "lucide" / "0.468.0" / "icons"
OUTPUT = ROOT / "src" / "lucide-icons.js"

# Keep this list deliberately small. The complete Lucide source catalog stays
# under vendor/ for offline reference; only icons used by Prestige and its
# bundled examples are embedded in the production runtime.
ICON_FILES = OrderedDict([
    ("activity", "activity"),
    ("ban", "ban"),
    ("chart-no-axes-column", "chart-no-axes-column"),
    ("bell", "bell"),
    ("blocks", "blocks"),
    ("bot", "bot"),
    ("calendar", "calendar"),
    ("circle", "circle"),
    ("circle-alert", "circle-alert"),
    ("circle-check", "circle-check"),
    ("circle-help", "circle-help"),
    ("check", "check"),
    ("cpu", "cpu"),
    ("database", "database"),
    ("file-text", "file-text"),
    ("folder-open", "folder-open"),
    ("gavel", "gavel"),
    ("gauge", "gauge"),
    ("git-branch", "git-branch"),
    ("history", "history"),
    ("info", "info"),
    ("key", "key"),
    ("layers", "layers"),
    ("layout-dashboard", "layout-dashboard"),
    ("library", "library"),
    ("list-checks", "list-checks"),
    ("log-out", "log-out"),
    ("message-square", "message-square"),
    ("message-square-more", "message-square-more"),
    ("package", "package"),
    ("panel-right", "panel-right"),
    ("panels-top-left", "panels-top-left"),
    ("route", "route"),
    ("save", "save"),
    ("scale", "scale"),
    ("scroll", "scroll"),
    ("search", "search"),
    ("search-check", "search-check"),
    ("settings", "settings"),
    ("shield-alert", "shield-alert"),
    ("sliders-horizontal", "sliders-horizontal"),
    ("sticky-note", "sticky-note"),
    ("table-properties", "table-properties"),
    ("text-cursor-input", "text-cursor-input"),
    ("thumbs-down", "thumbs-down"),
    ("triangle-alert", "triangle-alert"),
    ("upload", "upload"),
    ("user-cog", "user-cog"),
    ("user-plus", "user-plus"),
    ("user-round", "user-round"),
    ("users", "users"),
    ("wand-sparkles", "wand-sparkles"),
    ("x", "x"),
    ("zap-off", "zap-off"),
    ("arrow-down", "arrow-down"),
    ("hard-drive", "hard-drive"),
    ("lock", "lock"),
    ("mail", "mail"),
    ("monitor", "monitor"),
    ("thermometer", "thermometer"),
])


def compact_svg(path: Path) -> str:
    value = path.read_text("utf-8").strip()
    value = re.sub(r"<!--.*?-->", "", value, flags=re.DOTALL)
    value = re.sub(r">\s+<", "><", value)
    value = re.sub(r"\s{2,}", " ", value)
    return value


def main() -> None:
    missing = [source for source in ICON_FILES.values() if not (ICON_DIR / f"{source}.svg").is_file()]
    if missing:
        raise SystemExit(f"Missing pinned Lucide SVGs: {', '.join(missing)}")

    sources = OrderedDict()
    for public_name, source_name in ICON_FILES.items():
        sources[public_name] = compact_svg(ICON_DIR / f"{source_name}.svg")

    output = [
        "/* Generated by scripts/generate_icon_registry.py. Do not edit manually. */",
        "/* Source: vendor/lucide/0.468.0/icons; runtime registry is intentionally curated. */",
        "const ICONS = Object.freeze(" + json.dumps(sources, ensure_ascii=False, indent=4) + ");",
        "",
        "const DIALOG_ICON_NAMES = Object.freeze({",
        "    info: 'info', warning: 'triangle-alert', danger: 'circle-alert',",
        "    success: 'circle-check', question: 'circle-help', save: 'save',",
        "    open: 'folder-open', close: 'x', check: 'check',",
        "});",
        "",
        "function _safeIconName(name) {",
        "    return _resolveIconName(name);",
        "}",
        "",
        "function createIcon(name, attrs) {",
        "    const source = ICONS[_safeIconName(name)];",
        "    const parsed = new DOMParser().parseFromString(source, 'image/svg+xml');",
        "    const svg = document.importNode(parsed.documentElement, true);",
        "    svg.removeAttribute('width');",
        "    svg.removeAttribute('height');",
        "    const safeAttrs = attrs || {};",
        "    if (safeAttrs.class) svg.setAttribute('class', String(safeAttrs.class));",
        "    if (safeAttrs.title) svg.setAttribute('aria-label', String(safeAttrs.title));",
        "    if (safeAttrs['aria-hidden'] != null) svg.setAttribute('aria-hidden', String(safeAttrs['aria-hidden']));",
        "    if (safeAttrs.role) svg.setAttribute('role', String(safeAttrs.role));",
        "    return svg;",
        "}",
        "",
        "function _resolveIconName(name) {",
        "    var key = typeof name === 'string' ? name.trim().toLowerCase() : '';",
        "    if (Object.prototype.hasOwnProperty.call(ICONS, key)) return key;",
        "    return 'circle';",
        "}",
        "",
        "function _renderPlaceholder(placeholder, nameAttr) {",
        "    if (placeholder.getAttribute('data-prestige-rendered') === 'true') return;",
        "    var name = placeholder.getAttribute(nameAttr);",
        "    var resolved = _resolveIconName(name);",
        "    var svg = createIcon(resolved, {",
        "        class: placeholder.getAttribute('class') || '',",
        "        title: placeholder.getAttribute('title') || '',",
        "        'aria-hidden': placeholder.getAttribute('aria-hidden'),",
        "        role: placeholder.getAttribute('role') || '',",
        "    });",
        "    svg.setAttribute('data-prestige-icon', resolved);",
        "    svg.setAttribute('data-prestige-rendered', 'true');",
        "    placeholder.replaceWith(svg);",
        "}",
        "",
        "function renderIcons(root) {",
        "    var scope = root && root.querySelectorAll ? root : document;",
        "    scope.querySelectorAll('[data-prestige-icon]').forEach(function (el) { _renderPlaceholder(el, 'data-prestige-icon'); });",
        "    return scope;",
        "}",
        "",
        "function dialogIcon(name) {",
        "    return createIcon(DIALOG_ICON_NAMES[name] || name);",
        "}",
        "",
        "window.$icon = createIcon;",
        "window.PrestigeIcons = Object.freeze(Object.keys(ICONS));",
        "window.renderIcons = renderIcons;",
    ]
    OUTPUT.write_text("\n".join(output) + "\n", "utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)} with {len(sources)} curated icons")


if __name__ == "__main__":
    main()
